chore: replace CPEng with orb-publishers team in CODEOWNERS
CircleCI-Public/slack-orb pull request #379
Opened 2022-11-21 21:32 UTC by Jaryt

2022-11-21 21:32 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/slack?version=dev:bfe9afeae2c7d71838d0fc20befaa0b8424137fe

2022-11-22 18:29 UTC, EricRibeiro requested changes

2022-11-22 18:29 UTC, EricRibeiro commented on .github/CODEOWNERS
> +
Blank line.
```suggestion
```

2022-11-23 23:26 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/slack?version=dev:694351f84d9c7ef1da246e5c7ff38d4489e1f27f

2022-11-23 23:27 UTC, merged

2022-11-29 15:10 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/slack?version=dev:0edb427bc8cf33f5e3cbd654c8b34c3cfba2fd5e

2022-11-29 15:11 UTC, orb-publisher commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/slack?version=4.11.0